sudo: required
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev" # Python 3.8 development
install:
  - pip install -r requirements.txt
  - pip install -U pytest-flask
script: pytest
