language: python
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -U pytest-flask
script: pytest
python:
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: required
    - python: "3.8-dev"
      dist: xenial
      sudo: required
